%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.9 (R2020b) and Database Toolbox Version 10.0 on 29-Nov-2021 12:03:24

%% Make connection to database
conn = database('DB','USR','');

%Set query to execute on the database
query = ['SELECT date, ' ...
    '	mktrf, ' ...
    '	smb, ' ...
    '	hml, ' ...
    '	rf, ' ...
    '	umd, ' ...
    '	dateff ' ...
    'FROM wrds.ff_all.factors_monthly ' ...
    'WHERE date >= ''1975-01-01'''];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query