%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.9 (R2020b) and Database Toolbox Version 10.0 on 25-Jan-2021 00:16:27

%% Make connection to database
conn = database('DB','USER','PSWD');

%Set query to execute on the database
query = ['SELECT DISTINCT mflink2.fdate, ' ...
    '	mflink2.wficn, ' ...
    '	mflink1.crsp_fundno ' ...
    'FROM ( wrds.mfl.mflink2 ' ...
    'INNER JOIN wrds.mfl.mflink1 ' ...
    'ON mflink2.wficn = mflink1.wficn) ' ...
    'WHERE mflink2.ioc >= 2 ' ...
    '	AND mflink2.ioc <= 5 ' ...
    '	AND mflink2.country = ''UNITED STATES'''];

%% Execute query and fetch results
mfLink2 = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query